# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "minimal/trusty64"

  config.vm.define "slave" do |slave|
    slave.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.network "private_network", type: "dhcp"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
