# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  (1..2).each do |i|
    config.vm.define "slave_#{i}" do |slave|
      slave.vm.network "private_network", ip: "192.168.56.#{i+2}"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
end
