Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2010"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    # instala pacotes necesarios
    sudo apt-get -y update
    sudo apt-get -y upgrade
    sudo apt-get install -y python3.9
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python3 get-pip.py --user

    # sudo addgroup ansible
    # sudo useradd ansible \
    # -g ansible \
    # --home /home/ansible \
    # −−shell /bin/bash \
    
  SHELL

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.56.30"
    master.vm.provision "shell", inline: <<-SHELL
      python3 -m pip install --user ansible
  SHELL

  end
  config.vm.define "slave1" do |slave1|
    slave1.vm.network "private_network", ip: "192.168.56.31"
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.network "private_network", ip: "192.168.56.32"
  end
end
