Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "/Users/arthurresendefaria/desktop", "/vagrant_data"
end
