---
- stat:
    path: /etc/apt/sources.list.d/influxdata.list
  register: stat_result

- shell: "{{ comand }}"
  loop:
    - "wget -q https://repos.influxdata.com/influxdb.key"
    - "echo '23a1c8836f0afc5ed24e0486339d7cc8f6790b83886c4c96995b88a061c5bb5d influxdb.key' | sha256sum -c && cat influxdb.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null"
    - "echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list"
  loop_control:
    loop_var: comand
  when: stat_result.stat.exists == false

- apt:
    name: influxdb2
    update_cache: yes
    state: present

- service:
    name: influxdb
    state: started
    enabled: yes
...
