---
- name: Send PUT request to API
  hosts: localhost
  gather_facts: false
  vars:
    user: "admin"
    password: "eyJhbGciOiJIUzI1Ni"

  tasks:
  - name: send PUT request to API
    uri:
      url: http://localhost:5000/people/update
      method: PUT
      user: "{{ user }}"
      password: "{{ password }}"
      body_format: json
      body: {"id": 82, "email": "testebutchanged@gmail.com", "first_name": "Changed", "last_name": "Tester"}
      return_content: yes
    register: response
  
  - name: Prints response content
    debug:
      var: response
...