services:
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: /home/vagrant/atividade/prometheus
        target: /etc/prometheus
