file_type_list = {
    "Video files": ['.MPG', '.MOV', '.WMV', '.RM'],
    "Text Files":['.DOC', '.DOCX', '.EML', '.LOG','.MSG', '.ODT', '.PAGES', '.RTF', '.TEX', '.TXT','.WPD'],
    "Data Files":['.SDF', '.TAR', '.VCF', '.XML'],
    "Audio Files":['.AIF', '.FLAC', '.M3U', '.M4A', '.MID', '.MP3', '.OGG', '.WAV', '.WMA'],
    "Video Files":['.SWF', '.TS', '.VOB', '.WMV'],
    "Raster Image Files":['.PNG', '.PSD', '.TGA', '.TIF', '.JPG'],
    "Vector Image Files":['.AI', '.CDR', '.EMF', '.EPS', '.PS', '.SKETCH', '.SVG', '.VSDX'],
    "Page Layout Files":['.AFPUB', '.INDD', '.OXPS', '.PDF', '.PMD', '.PUB', '.QXP', '.XPS'],
    "Spreadsheet Files":['.NUMBERS', '.ODS', '.XLR', '.XLS', '.XLSX'],
    "Executable Files":['.JAR', '.RUN', '.SH'],
    "Game Files":['.BIN', '.DEM', '.GAM', '.GBA', '.NES', '.PAK', '.PKG', '.ROM', '.SAV', '.SAV'],
    "Web Files":['.CSR', '.CSS', '.HTML', '.JS', '.JSON', '.JSP', '.PHP', '.XHTML'],
    "Font Files":['.FNT', '.OTF', '.TTF', '.WOFF', '.WOFF2'],
    "System Files":['.DLL', '.DMP', '.DRV', '.ICNS', '.ICO', '.LNK', '.REG', '.SYS'],
    "Settings Files":['.CFG', '.INI', '.PKG', '.PRF', '.SET'],
    "Encoded Files":['.ASC', '.BIN', '.ENC', '.MIM', '.UUE'],
    "Compressed Files":['.PKG', '.RAR', '.RPM', '.gz">.TAR.GZ', '.XAPK', '.ZIP', '.ZIPX'],
    "Disk Image Files":['.BIN', '.DMG', '.IMG', '.ISO', '.MDF', '.ROM', '.VCD', '.VMDK'],
    "Developer Files":['.KT', '.LUA', '.M', '.MD', '.PL', '.PY', '.SB3', '.SLN', '.SWIFT', '.UNITY', '.VB','.VCXPROJ', '.XCODEPROJ', '.YML'],
    "Backup Files":['.ABK', '.ARC', '.BAK', '.TMP'],
    "Misc Files":['.CRDOWNLOAD', '.ICS', '.MSI', '.NOMEDIA', '.PART', '.PKPASS', '.TORRENT'],
}